"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { formatKES } from "@/lib/format";
import type { FieldSpec } from "@/lib/pos/forms";
import type { EmptyState } from "@/lib/pos/presentation";

/**
 * One records screen for every entity (§24, §52).
 *
 * Products, customers, suppliers, staff and expenses are all drawn by this component. What
 * differs between them — and between trades — is the field list the server generated from the
 * configuration. Adding a business type therefore never means adding a screen.
 */

export type RecordRow = Record<string, any> & { id: string };

export type ValueColumn = { key: string; label?: string; money?: boolean; suffix?: string };

type Props = {
  businessId: string;
  apiPath: string;
  word: string;
  plural: string;
  fields: FieldSpec[];
  rows: RecordRow[];
  titleKey: string;
  subtitleKeys?: string[];
  valueColumns?: ValueColumn[];
  canEdit: boolean;
  /** Creating and editing rows can be separate rights: an expense may be added but never edited (§54). */
  canCreate?: boolean;
  canEditRow?: boolean;
  canArchive?: boolean;
  /** Teaching empty state (§60) — generated by the engine from the configuration. */
  emptyState: EmptyState;
  searchPlaceholder?: string;
  openNew?: boolean;
  basePath: string;
  detailPath?: string;
  /** PATCH `${apiPath}/${id}` (most entities) or POST with an id field (staff). */
  updateMode?: "patch" | "post";
  updateIdKey?: string;
  /** Options for select fields that come from other records (suppliers, branches, products). */
  optionSets?: Record<string, { id: string; label: string }[]>;
  extra?: React.ReactNode;
};

function initialValue(field: FieldSpec): string | number | boolean {
  if (field.defaultValue !== undefined) return field.defaultValue;
  if (field.kind === "toggle") return false;
  if (field.kind === "number" || field.kind === "money") return 0;
  return "";
}

function emptyForm(fields: FieldSpec[]): Record<string, string | number | boolean> {
  const values: Record<string, string | number | boolean> = {};
  for (const field of fields) values[field.key] = initialValue(field);
  return values;
}

function rowForm(fields: FieldSpec[], row: RecordRow): Record<string, string | number | boolean> {
  const values = emptyForm(fields);
  for (const field of fields) {
    const raw = row[field.key];
    if (raw === undefined || raw === null) continue;
    if (typeof raw === "boolean" || typeof raw === "number") values[field.key] = raw;
    else if (raw instanceof Date) values[field.key] = raw.toISOString().slice(0, 10);
    else values[field.key] = String(raw);
  }
  return values;
}

export function RecordBoard(props: Props) {
  const {
    businessId, apiPath, word, plural, fields, rows, titleKey, subtitleKeys = [], valueColumns = [],
    canEdit, canArchive = false, emptyState, searchPlaceholder, openNew = false, basePath, detailPath,
    updateMode = "patch", updateIdKey = "id", optionSets = {},
  } = props;

  const canCreate = props.canCreate ?? canEdit;
  const canEditRow = props.canEditRow ?? canEdit;
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<RecordRow | null>(null);
  const [creating, setCreating] = useState(openNew);
  const [values, setValues] = useState<Record<string, string | number | boolean>>(() => emptyForm(fields));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saved, setSaved] = useState<string | null>(null);

  useEffect(() => {
    if (openNew) startCreate();
    // Only on first render: the query flag opens the form once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const visible = useMemo(() => {
    const term = search.trim().toLowerCase();
    if (!term) return rows;
    return rows.filter((row) =>
      [titleKey, ...subtitleKeys, ...valueColumns.map((column) => column.key)]
        .some((key) => String(row[key] ?? "").toLowerCase().includes(term)),
    );
  }, [rows, search, titleKey, subtitleKeys, valueColumns]);

  function startCreate() {
    setEditing(null);
    setCreating(true);
    setValues(emptyForm(fields));
    setError(null);
    setSaved(null);
  }

  function startEdit(row: RecordRow) {
    setEditing(row);
    setCreating(true);
    setValues(rowForm(fields, row));
    setError(null);
    setSaved(null);
  }

  function close() {
    setCreating(false);
    setEditing(null);
    setError(null);
  }

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setBusy(true);
    setError(null);
    setSaved(null);
    const payload: Record<string, unknown> = {};
    for (const field of fields) {
      const value = values[field.key];
      if (field.kind === "toggle") payload[field.key] = Boolean(value);
      else if (field.kind === "number" || field.kind === "money") payload[field.key] = Number(value || 0);
      else if (value === "" || value === undefined) continue;
      else payload[field.key] = value;
    }
    if (editing) payload[updateIdKey] = editing.id;

    try {
      const response = await fetch(updateMode === "patch" && editing ? `${apiPath}/${encodeURIComponent(editing.id)}` : apiPath, {
        method: updateMode === "patch" && editing ? "PATCH" : "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = await response.json();
      if (!response.ok || data?.ok === false) {
        setError(data?.error ?? `We couldn't save that ${word.toLowerCase()}.`);
        setBusy(false);
        return;
      }
      setSaved(data?.warnings?.length ? data.warnings.join(" ") : `Saved. ${editing ? "Updated" : "Added"} ${word.toLowerCase()}.`);
      setBusy(false);
      setCreating(false);
      setEditing(null);
      window.location.reload();
    } catch {
      setError("We couldn't reach JATA. Check your connection and try again.");
      setBusy(false);
    }
  }

  async function archive(row: RecordRow) {
    setBusy(true);
    setError(null);
    try {
      const response = await fetch(`${apiPath}/${encodeURIComponent(row.id)}`, {
        method: "PATCH",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ archive: true, name: row[titleKey] }),
      });
      const data = await response.json();
      if (!response.ok) setError(data?.error ?? "We couldn't remove that.");
      else window.location.reload();
    } catch {
      setError("We couldn't reach JATA. Check your connection and try again.");
    } finally {
      setBusy(false);
    }
  }

  const groups = ["", ...fields.map((field) => field.group ?? "").filter((group, index, all) => group && all.indexOf(group) === index)];

  return (
    <div className="space-y-4">
      <div className="pos-toolbar">
        <input
          className="jata-input pos-search"
          type="search"
          value={search}
          onChange={(event) => setSearch(event.target.value)}
          placeholder={searchPlaceholder ?? `Search ${plural.toLowerCase()}…`}
          aria-label={`Search ${plural.toLowerCase()}`}
        />
        {canCreate ? (
          <button type="button" className="jata-btn jata-btn-primary" onClick={startCreate}>+ Add {word.toLowerCase()}</button>
        ) : null}
      </div>

      {saved ? <p className="pos-note" role="status">{saved}</p> : null}
      {error ? <p className="jata-error" role="alert">{error}</p> : null}

      {creating ? (
        <form className="jata-card p-5 pos-form" onSubmit={submit}>
          <div>
            <p className="jata-kicker">{editing ? `Edit ${word.toLowerCase()}` : `Add ${word.toLowerCase()}`}</p>
            <h2 className="text-lg font-bold">{editing ? String(editing[titleKey] ?? word) : `New ${word.toLowerCase()}`}</h2>
          </div>

          {groups.map((group) => (
            <div className="pos-form-group" key={group || "main"}>
              {group ? <h3>{group}</h3> : null}
              <div className="pos-grid-2">
                {fields
                  .filter((field) => (field.group ?? "") === group)
                  .map((field) => (
                    <div className="jata-field" key={field.key}>
                      <label className="jata-label" htmlFor={`f-${field.key}`}>
                        {field.label}{field.required ? " *" : ""}
                      </label>
                      {field.kind === "toggle" ? (
                        <label className="pos-chip" data-on={Boolean(values[field.key])}>
                          <input
                            id={`f-${field.key}`}
                            type="checkbox"
                            checked={Boolean(values[field.key])}
                            onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.checked }))}
                          />
                          {values[field.key] ? "Yes" : "No"}
                        </label>
                      ) : field.kind === "select" ? (
                        <select
                          id={`f-${field.key}`}
                          className="jata-input"
                          value={String(values[field.key] ?? "")}
                          onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))}
                        >
                          {(field.options?.length ? field.options : optionSets[field.key] ?? []).map((option) => (
                            <option key={option.id} value={option.id}>{option.label}</option>
                          ))}
                        </select>
                      ) : field.kind === "textarea" ? (
                        <textarea
                          id={`f-${field.key}`}
                          className="jata-input"
                          rows={3}
                          placeholder={field.placeholder}
                          value={String(values[field.key] ?? "")}
                          onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))}
                        />
                      ) : (
                        <input
                          id={`f-${field.key}`}
                          className="jata-input"
                          type={field.kind === "number" || field.kind === "money" ? "number" : field.kind === "phone" ? "tel" : field.kind === "email" ? "email" : field.kind === "date" ? "date" : field.kind === "datetime" ? "datetime-local" : "text"}
                          inputMode={field.kind === "money" || field.kind === "number" ? "numeric" : undefined}
                          min={field.kind === "money" || field.kind === "number" ? 0 : undefined}
                          placeholder={field.kind === "money" ? "0" : field.placeholder}
                          required={field.required}
                          value={String(values[field.key] ?? "")}
                          onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))}
                        />
                      )}
                      {field.hint ? <p className="jata-hint">{field.hint}</p> : null}
                      {field.kind === "money" ? <p className="jata-hint">In Kenyan shillings.</p> : null}
                    </div>
                  ))}
              </div>
            </div>
          ))}

          <div className="pos-form-actions">
            <button type="submit" className="jata-btn jata-btn-primary" disabled={busy}>
              {busy ? "Saving…" : editing ? "Save changes" : `Add ${word.toLowerCase()}`}
            </button>
            <button type="button" className="jata-btn jata-btn-ghost" onClick={close}>Cancel</button>
          </div>
        </form>
      ) : null}

      {props.extra}

      {visible.length === 0 ? (
        <div className="pos-empty">
          <strong>{rows.length === 0 ? emptyState.title : `Nothing matches “${search}”`}</strong>
          <p>{rows.length === 0 ? emptyState.body : "Try a different word."}</p>
          {rows.length === 0 && canCreate ? (
            <button type="button" className="jata-btn jata-btn-primary" onClick={startCreate}>{emptyState.action.label}</button>
          ) : null}
          {rows.length === 0 && !canCreate && basePath ? (
            <Link href={basePath} className="jata-btn jata-btn-secondary">Back to dashboard</Link>
          ) : null}
        </div>
      ) : (
        <div className="pos-rows">
          {visible.map((row) => (
            <div className="pos-row" key={row.id}>
              <div className="pos-row-main">
                {detailPath ? (
                  <Link href={`${basePath}/${detailPath}/${row.id}`}><strong>{String(row[titleKey] ?? "—")}</strong></Link>
                ) : (
                  <strong>{String(row[titleKey] ?? "—")}</strong>
                )}
                {subtitleKeys.length ? (
                  <small>{subtitleKeys.map((key) => row[key]).filter(Boolean).join(" · ")}</small>
                ) : null}
              </div>
              <div className="pos-row-values">
                {valueColumns.map((column) => (
                  <span key={column.key}>
                    {column.money ? formatKES(Number(row[column.key] ?? 0)) : String(row[column.key] ?? "")}
                    {column.suffix ? ` ${column.suffix}` : ""}
                  </span>
                ))}
              </div>
              {canEditRow ? (
                <div className="pos-row-actions">
                  <button type="button" className="jata-btn jata-btn-ghost" onClick={() => startEdit(row)}>Edit</button>
                  {canArchive ? (
                    <button type="button" className="jata-btn jata-btn-ghost" onClick={() => archive(row)} disabled={busy}>Remove</button>
                  ) : null}
                </div>
              ) : null}
            </div>
          ))}
        </div>
      )}

      <p className="pos-note" aria-live="polite">
        {visible.length} of {rows.length} {plural.toLowerCase()}
        {businessId ? "" : ""}
      </p>
    </div>
  );
}
